ALTER TABLE ERS_USERS DROP CONSTRAINT ERS_USERS_FK_UR_ID;
ALTER TABLE ERS_REIMBURSEMENTS DROP CONSTRAINT ERS_REIMBURSEMENTS_FK_AUTHOR;
ALTER TABLE ERS_REIMBURSEMENTS DROP CONSTRAINT ERS_REIMBURSEMENTS_FK_RESOLVER;
ALTER TABLE ERS_REIMBURSEMENTS DROP CONSTRAINT ERS_REIMBURSEMENTS_FK_TYPE;
ALTER TABLE ERS_REIMBURSEMENTS DROP CONSTRAINT ERS_REIMBURSEMENTS_FK_STATUS;

DROP TABLE ERS_USERS;
DROP TABLE ERS_USER_ROLES;
DROP TABLE ERS_REIMBURSEMENTS;
DROP TABLE ERS_REIMBURSEMENT_STATUS;
DROP TABLE ERS_REIMBURSEMENT_TYPE;

CREATE TABLE ERS_USERS (
    U_ID NUMBER(*, 0) PRIMARY KEY,
    U_USERNAME VARCHAR2(40 BYTE) UNIQUE NOT NULL,
    U_PASSWORD VARCHAR2 (40 BYTE) NOT NULL,
    U_FIRSTNAME VARCHAR2 (30 BYTE),
    U_LASTNAME VARCHAR2 (30 BYTE),
    U_EMAIL VARCHAR2 (100 BYTE) UNIQUE,
    UR_ID NUMBER (*, 0) NOT NULL
);

CREATE TABLE ERS_USER_ROLES (
    UR_ID NUMBER (*, 0) PRIMARY KEY,
    UR_ROLE VARCHAR2 (40 BYTE)
);

CREATE TABLE ERS_REIMBURSEMENTS (
    R_ID NUMBER (*, 0) PRIMARY KEY,
    R_AMOUNT NUMBER (22,2) NOT NULL,
    R_DESCRIPTION VARCHAR2 (100 BYTE),
    R_RECIEPT BLOB,
    R_SUBMITTED TIMESTAMP NOT NULL,
    R_RESOLVED TIMESTAMP,
    U_ID_AUTHOR NUMBER (*, 0) NOT NULL,
    U_ID_RESOLVER NUMBER (*, 0),
    RT_TYPE NUMBER (*, 0) NOT NULL,
    RT_STATUS NUMBER (*, 0) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_STATUS (
    RS_ID NUMBER (*, 0) PRIMARY KEY,
    RS_STATUS VARCHAR2 (30 BYTE) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE (
    RT_ID NUMBER (*, 0) PRIMARY KEY,
    RT_TYPE VARCHAR2 (30 BYTE) NOT NULL
);

CREATE SEQUENCE U_Sequence START WITH 1 INCREMENT BY 3;
CREATE SEQUENCE R_Sequence START WITH 1 INCREMENT BY 1;

ALTER TABLE ERS_USERS ADD CONSTRAINT ERS_USERS_FK_UR_ID 
FOREIGN KEY (UR_ID) REFERENCES ERS_USER_ROLES (UR_ID);

ALTER TABLE ERS_REIMBURSEMENTS ADD CONSTRAINT ERS_REIMBURSEMENTS_FK_AUTHOR
FOREIGN KEY (U_ID_AUTHOR) REFERENCES ERS_USERS (U_ID);

ALTER TABLE ERS_REIMBURSEMENTS ADD CONSTRAINT ERS_REIMBURSEMENTS_FK_RESOLVER
FOREIGN KEY (U_ID_RESOLVER) REFERENCES ERS_USERS (U_ID);

ALTER TABLE ERS_REIMBURSEMENTS ADD CONSTRAINT ERS_REIMBURSEMENTS_FK_TYPE
FOREIGN KEY (RT_TYPE) REFERENCES ERS_REIMBURSEMENT_TYPE (RT_ID);

ALTER TABLE ERS_REIMBURSEMENTS ADD CONSTRAINT ERS_REIMBURSEMENTS_FK_STATUS
FOREIGN KEY (RT_STATUS) REFERENCES ERS_REIMBURSEMENT_STATUS (RS_ID);

INSERT INTO ERS_USER_ROLES VALUES (1, 'Manager');
INSERT INTO ERS_USER_ROLES VALUES (2, 'Employee');
INSERT INTO ERS_USERS VALUES (1, 'TIM', 'DEFAULT', 'TIMOTHY', 'DECKERT', 'TADECKERT7@GMAIL.COM', 1);
INSERT INTO ERS_USERS VALUES (2, 'TOM', 'DEFAULT', 'DARIA', 'DAVALOO', 'DDAVALOO24@GMAIL.COM', 2);
INSERT INTO ERS_REIMBURSEMENT_STATUS VALUES (1, 'Pending');
INSERT INTO ERS_REIMBURSEMENT_STATUS VALUES (2, 'Approved');
INSERT INTO ERS_REIMBURSEMENT_STATUS VALUES (3, 'Denied');
INSERT INTO ERS_REIMBURSEMENT_TYPE VALUES (1, 'Medical');
INSERT INTO ERS_REIMBURSEMENT_TYPE VALUES (2, 'Travel');
INSERT INTO ERS_REIMBURSEMENT_TYPE VALUES (3, 'Business');
--INSERT INTO ERS_REIMBURSEMENTS (R_ID, R_AMOUNT, R_DESCRIPTION, U_ID_AUTHOR, RT_TYPE, RT_STATUS) VALUES (1, 20.00, 'travel to costa rica', 1, 2, 1);
--INSERT INTO ERS_REIMBURSEMENTS (R_ID, R_AMOUNT, R_DESCRIPTION, U_ID_AUTHOR, RT_TYPE, RT_STATUS) VALUES (2, 30.00, 'travel to costa rica', 1, 2, 2);
--INSERT INTO ERS_REIMBURSEMENTS (R_ID, R_AMOUNT, R_DESCRIPTION, U_ID_AUTHOR, RT_TYPE, RT_STATUS) VALUES (3, 40.00, 'travel to costa rica', 1, 2, 3);